name: 'Terraform Azure Provisioning'

on:
  push:
    branches:
      - main
jobs:
   terraform:
    runs-on: self-hosted
    defaults:
        run:
            shell: bash
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Print GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: Generate backend configuration
        run: |
         cat > /home/admin2025/actions-runner/_work/self-service-prod/self-service-prod/terraform/backend.tf <<EOF
         terraform {
           backend "azurerm" {
              resource_group_name = "${{ secrets.AZURE_RESOURCE_GROUP }}"
              storage_account_name = "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
              container_name = "${{ secrets.AZURE_CONTAINER_NAME }}"
              key = "${{ secrets.AZURE_KEY }}"
           } 
         } 
         EOF
          
      - name: Opentofu Init
        run: |
           az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           tofu init -migrate-state
        working-directory: /home/admin2025/actions-runner/_work/self-service-prod/self-service-prod/terraform
        
      # - name: Terraform Validate
      #   run: terraform validate
      #   working-directory: /home/admin2025/actions-runner/_work/self-service-prod/self-service-prod/terraform

      # - name: Terraform format
      #   run: terraform fmt
      #   working-directory: /home/admin2025/actions-runner/_work/self-service-prod/self-service-prod/terraform
      
      - name: Opentofu Plan
        run: tofu plan -out=tfplan
        working-directory: /home/admin2025/actions-runner/_work/self-service-prod/self-service-prod/terraform


      - name: Opentofu Apply
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve tfplan
        working-directory: /home/admin2025/actions-runner/_work/self-service-prod/self-service-prod/terraform
   
