name: 'Terraform Azure Provisioning'

on:
  push:
    branches:
      - main
jobs:
   terraform:
    runs-on: self-hosted
    defaults:
        run:
            shell: bash
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Print GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
         terraform_version: 1.11.4
         
      - name: Terraform Init
        run: terraform init
        working-directory: /home/admin2025/actions-runner/_work/terraform2/terraform2/terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: /home/admin2025/actions-runner/_work/terraform2/terraform2/terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: /home/admin2025/actions-runner/_work/terraform2/terraform2/terraform
